[2024-05-18T14:11:37.391+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:11:37.410+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:11:37.427+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:11:37.426+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:11:37.780+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:11:37.768+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:11:37.793+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:11:37.900+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.612 seconds
[2024-05-18T14:12:08.152+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:12:08.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:12:08.159+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:12:08.159+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:12:08.202+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:12:08.193+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:12:08.205+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:12:08.237+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.090 seconds
[2024-05-18T14:12:38.632+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:12:38.633+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:12:38.635+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:12:38.635+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:12:38.666+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:12:38.659+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:12:38.669+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:12:38.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.066 seconds
[2024-05-18T14:13:09.033+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:13:09.034+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:13:09.037+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:13:09.036+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:13:09.066+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:13:09.060+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:13:09.068+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:13:09.096+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.067 seconds
[2024-05-18T14:13:39.449+0000] {processor.py:161} INFO - Started process (PID=79) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:13:39.451+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:13:39.454+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:13:39.454+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:13:39.494+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:13:39.486+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:13:39.497+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:13:39.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.089 seconds
[2024-05-18T14:14:09.906+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:14:09.907+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:14:09.910+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:14:09.910+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:14:09.951+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:14:09.944+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:14:09.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:14:09.985+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.083 seconds
[2024-05-18T14:14:40.339+0000] {processor.py:161} INFO - Started process (PID=95) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:14:40.341+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:14:40.345+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:14:40.344+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:14:40.377+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:14:40.371+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:14:40.379+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:14:40.406+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.072 seconds
[2024-05-18T14:15:10.776+0000] {processor.py:161} INFO - Started process (PID=103) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:15:10.778+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:15:10.783+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:15:10.782+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:15:10.827+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:15:10.817+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:15:10.831+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:15:10.870+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.100 seconds
[2024-05-18T14:15:41.240+0000] {processor.py:161} INFO - Started process (PID=111) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:15:41.242+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:15:41.246+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:15:41.246+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:15:41.277+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:15:41.271+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:15:41.281+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:15:41.310+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.073 seconds
[2024-05-18T14:16:11.671+0000] {processor.py:161} INFO - Started process (PID=119) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:16:11.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:16:11.675+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:16:11.675+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:16:11.706+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:16:11.700+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:16:11.708+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:16:11.738+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.072 seconds
[2024-05-18T14:16:42.155+0000] {processor.py:161} INFO - Started process (PID=127) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:16:42.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:16:42.161+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:16:42.160+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:16:42.189+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:16:42.183+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:16:42.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:16:42.218+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.066 seconds
[2024-05-18T14:17:12.560+0000] {processor.py:161} INFO - Started process (PID=135) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:17:12.561+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:17:12.564+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:17:12.564+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:17:12.599+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:17:12.591+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:17:12.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:17:12.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.075 seconds
[2024-05-18T14:17:42.990+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:17:42.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:17:42.994+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:17:42.994+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:17:43.023+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:17:43.017+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:17:43.025+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:17:43.053+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.067 seconds
[2024-05-18T14:18:13.385+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:18:13.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:18:13.390+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:18:13.390+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:18:13.417+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:18:13.412+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:18:13.421+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:18:13.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.066 seconds
[2024-05-18T14:18:43.795+0000] {processor.py:161} INFO - Started process (PID=159) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:18:43.796+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:18:43.798+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:18:43.798+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:18:43.831+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:18:43.824+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:18:43.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:18:43.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.070 seconds
[2024-05-18T14:20:41.039+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:20:41.045+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:20:41.052+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:20:41.051+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:20:41.138+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:20:41.124+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:20:41.143+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:20:41.208+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.180 seconds
[2024-05-18T14:21:11.489+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:21:11.490+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:21:11.494+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:21:11.493+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:21:11.523+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:21:11.517+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:21:11.526+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:21:11.555+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.072 seconds
[2024-05-18T14:21:41.895+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:21:41.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:21:41.899+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:21:41.898+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:21:41.928+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:21:41.922+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:21:41.931+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:21:41.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.064 seconds
[2024-05-18T14:22:12.328+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:22:12.330+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:22:12.332+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:22:12.332+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:22:12.360+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:22:12.354+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:22:12.362+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:22:12.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.063 seconds
[2024-05-18T14:22:42.726+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:22:42.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:22:42.730+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:22:42.730+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:22:42.760+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:22:42.753+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:22:42.762+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:22:42.792+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.069 seconds
[2024-05-18T14:58:50.422+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:58:50.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:58:50.432+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:58:50.431+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:58:50.615+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:58:50.564+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:58:50.624+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:58:50.700+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.298 seconds
[2024-05-18T14:59:22.270+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:59:22.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:59:22.347+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:59:22.341+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:59:22.666+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:59:22.591+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:59:22.706+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:59:23.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 1.047 seconds
[2024-05-18T14:59:54.427+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:59:54.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T14:59:54.452+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:59:54.450+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:59:54.578+0000] {logging_mixin.py:188} INFO - [2024-05-18T14:59:54.548+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T14:59:54.593+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T14:59:54.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.358 seconds
[2024-05-18T15:00:25.386+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:00:25.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T15:00:25.410+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:00:25.409+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:00:25.573+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:00:25.546+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T15:00:25.581+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:00:25.710+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.356 seconds
[2024-05-18T15:00:56.508+0000] {processor.py:161} INFO - Started process (PID=76) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:00:56.530+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T15:00:56.551+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:00:56.550+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:00:56.836+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:00:56.766+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T15:00:56.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:00:56.998+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.537 seconds
[2024-05-18T15:01:28.054+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:01:28.058+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T15:01:28.075+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:01:28.074+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:01:28.372+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:01:28.300+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T15:01:28.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:01:28.547+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.553 seconds
[2024-05-18T15:01:58.994+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:01:59.009+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T15:01:59.017+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:01:59.015+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:01:59.555+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:01:59.208+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T15:01:59.650+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:01:59.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.882 seconds
[2024-05-18T15:02:30.815+0000] {processor.py:161} INFO - Started process (PID=99) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:02:30.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T15:02:30.916+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:02:30.912+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:02:31.123+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:02:31.103+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T15:02:31.127+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:02:31.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.594 seconds
[2024-05-18T15:03:02.205+0000] {processor.py:161} INFO - Started process (PID=113) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:03:02.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T15:03:02.221+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:03:02.220+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:03:02.353+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:03:02.324+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T15:03:02.365+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:03:02.483+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.299 seconds
[2024-05-18T15:14:03.968+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:14:03.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T15:14:03.994+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:14:03.993+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:14:04.088+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:14:04.071+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T15:14:04.093+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:14:04.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.284 seconds
[2024-05-18T15:14:34.614+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:14:34.615+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T15:14:34.618+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:14:34.617+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:14:34.649+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:14:34.641+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T15:14:34.652+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:14:34.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.071 seconds
[2024-05-18T15:15:05.273+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:15:05.275+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T15:15:05.279+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:15:05.279+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:15:05.328+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:15:05.318+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T15:15:05.332+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:15:05.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.101 seconds
[2024-05-18T15:15:35.740+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:15:35.742+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T15:15:35.745+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:15:35.744+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:15:35.802+0000] {logging_mixin.py:188} INFO - [2024-05-18T15:15:35.791+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T15:15:35.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T15:15:35.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.108 seconds
[2024-05-18 22:35:13,383] {processor.py:153} INFO - Started process (PID=82) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18 22:35:13,388] {processor.py:641} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18 22:35:13,418] {logging_mixin.py:115} INFO - [2024-05-18 22:35:13,418] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18 22:35:15,816] {logging_mixin.py:115} INFO - [2024-05-18 22:35:15,773] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18 22:35:15,822] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18 22:35:16,055] {processor.py:161} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 2.691 seconds
[2024-05-18T22:42:30.515+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:42:30.528+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:42:30.589+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:42:30.588+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:42:30.868+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:42:30.827+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:42:30.895+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:42:31.064+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.625 seconds
[2024-05-18T22:43:24.249+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:43:24.254+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:43:24.262+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:43:24.261+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:43:24.388+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:43:24.341+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:43:24.397+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:43:24.484+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.265 seconds
[2024-05-18T22:43:55.936+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:43:55.939+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:43:55.945+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:43:55.944+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:43:56.029+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:43:56.003+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:43:56.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:43:56.164+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.255 seconds
[2024-05-18T22:44:26.954+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:44:26.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:44:26.960+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:44:26.960+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:44:27.011+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:44:26.999+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:44:27.015+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:44:27.056+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.116 seconds
[2024-05-18T22:44:57.621+0000] {processor.py:161} INFO - Started process (PID=285) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:44:57.623+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:44:57.625+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:44:57.625+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:44:57.661+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:44:57.653+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:44:57.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:44:57.695+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.082 seconds
[2024-05-18T22:45:27.879+0000] {processor.py:161} INFO - Started process (PID=345) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:45:27.880+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:45:27.883+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:45:27.882+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:45:27.913+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:45:27.907+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:45:27.916+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:45:27.946+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.074 seconds
[2024-05-18T22:45:58.127+0000] {processor.py:161} INFO - Started process (PID=405) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:45:58.129+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:45:58.132+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:45:58.131+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:45:58.168+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:45:58.159+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:45:58.171+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:45:58.206+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.088 seconds
[2024-05-18T22:46:28.796+0000] {processor.py:161} INFO - Started process (PID=465) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:46:28.798+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:46:28.801+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:46:28.800+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:46:28.835+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:46:28.827+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:46:28.839+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:46:28.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.088 seconds
[2024-05-18T22:46:59.309+0000] {processor.py:161} INFO - Started process (PID=525) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:46:59.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:46:59.317+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:46:59.316+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:46:59.360+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:46:59.351+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:46:59.364+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:46:59.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.105 seconds
[2024-05-18T22:47:29.750+0000] {processor.py:161} INFO - Started process (PID=585) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:47:29.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:47:29.759+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:47:29.758+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:47:29.811+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:47:29.801+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:47:29.818+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:47:29.878+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.144 seconds
[2024-05-18T22:48:00.801+0000] {processor.py:161} INFO - Started process (PID=645) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:48:00.804+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:48:00.813+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:48:00.809+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:48:00.878+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:48:00.866+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:48:00.883+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:48:00.932+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.155 seconds
[2024-05-18T22:48:31.968+0000] {processor.py:161} INFO - Started process (PID=705) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:48:31.980+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:48:32.005+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:48:32.000+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:48:32.406+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:48:32.333+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:48:32.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:48:32.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.992 seconds
[2024-05-18T22:49:03.352+0000] {processor.py:161} INFO - Started process (PID=765) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:49:03.354+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:49:03.357+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:49:03.356+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:49:03.390+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:49:03.383+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:49:03.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:49:03.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.080 seconds
[2024-05-18T22:49:33.694+0000] {processor.py:161} INFO - Started process (PID=825) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:49:33.695+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:49:33.699+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:49:33.698+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:49:33.742+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:49:33.732+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:49:33.747+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:49:33.780+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.095 seconds
[2024-05-18T22:50:04.093+0000] {processor.py:161} INFO - Started process (PID=885) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:50:04.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:50:04.099+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:50:04.099+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:50:04.154+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:50:04.140+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:50:04.160+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:50:04.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.120 seconds
[2024-05-18T22:50:35.345+0000] {processor.py:161} INFO - Started process (PID=945) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:50:35.348+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:50:35.355+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:50:35.354+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:50:35.429+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:50:35.414+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:50:35.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:50:35.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.182 seconds
[2024-05-18T22:51:06.493+0000] {processor.py:161} INFO - Started process (PID=1003) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:51:06.502+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:51:06.506+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:51:06.505+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:51:06.573+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:51:06.562+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:51:06.583+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:51:06.645+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.165 seconds
[2024-05-18T22:51:37.260+0000] {processor.py:161} INFO - Started process (PID=1062) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:51:37.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:51:37.265+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:51:37.264+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:51:37.300+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:51:37.292+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:51:37.304+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:51:37.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.082 seconds
[2024-05-18T22:52:07.477+0000] {processor.py:161} INFO - Started process (PID=1122) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:52:07.479+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:52:07.483+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:52:07.482+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:52:07.532+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:52:07.520+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:52:07.536+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:52:07.591+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.122 seconds
[2024-05-18T22:57:49.901+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:57:49.904+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:57:49.909+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:57:49.908+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:57:50.003+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:57:49.988+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:57:50.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:57:50.078+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.193 seconds
[2024-05-18T22:58:20.531+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:58:20.534+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:58:20.538+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:58:20.538+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:58:20.609+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:58:20.591+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:58:20.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:58:20.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.171 seconds
[2024-05-18T22:58:51.157+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:58:51.158+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:58:51.162+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:58:51.162+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:58:51.214+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:58:51.202+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:58:51.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:58:51.258+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.110 seconds
[2024-05-18T22:59:21.639+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:59:21.640+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:59:21.644+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:59:21.643+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:59:21.674+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:59:21.668+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:59:21.678+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:59:21.707+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.074 seconds
[2024-05-18T22:59:52.064+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:59:52.066+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T22:59:52.069+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:59:52.069+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:59:52.102+0000] {logging_mixin.py:188} INFO - [2024-05-18T22:59:52.094+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T22:59:52.106+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T22:59:52.139+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.084 seconds
[2024-05-18T23:00:22.490+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:00:22.491+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:00:22.494+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:00:22.494+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:00:22.518+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:00:22.513+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:00:22.520+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:00:22.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.064 seconds
[2024-05-18T23:00:52.940+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:00:52.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:00:52.945+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:00:52.944+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:00:53.004+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:00:52.993+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:00:53.008+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:00:53.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.117 seconds
[2024-05-18T23:01:23.444+0000] {processor.py:161} INFO - Started process (PID=97) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:01:23.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:01:23.450+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:01:23.449+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:01:23.500+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:01:23.485+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:01:23.505+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:01:23.543+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.108 seconds
[2024-05-18T23:01:53.887+0000] {processor.py:161} INFO - Started process (PID=105) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:01:53.888+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:01:53.892+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:01:53.891+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:01:53.932+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:01:53.924+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:01:53.937+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:01:53.975+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.097 seconds
[2024-05-18T23:02:24.812+0000] {processor.py:161} INFO - Started process (PID=112) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:02:24.814+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:02:24.819+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:02:24.818+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:02:24.901+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:02:24.880+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:02:24.909+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:02:24.992+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.195 seconds
[2024-05-18T23:02:55.860+0000] {processor.py:161} INFO - Started process (PID=120) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:02:55.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:02:55.866+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:02:55.865+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:02:55.912+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:02:55.902+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:02:55.916+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:02:55.961+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.114 seconds
[2024-05-18T23:03:26.193+0000] {processor.py:161} INFO - Started process (PID=128) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:03:26.195+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:03:26.198+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:03:26.198+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:03:26.270+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:03:26.257+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:03:26.275+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:03:26.334+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.153 seconds
[2024-05-18T23:03:57.443+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:03:57.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:03:57.486+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:03:57.485+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:03:57.542+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:03:57.531+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:03:57.549+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:03:57.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.178 seconds
[2024-05-18T23:04:28.206+0000] {processor.py:161} INFO - Started process (PID=144) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:04:28.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:04:28.212+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:04:28.211+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:04:28.270+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:04:28.257+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:04:28.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:04:28.318+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.123 seconds
[2024-05-18T23:04:58.945+0000] {processor.py:161} INFO - Started process (PID=152) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:04:58.948+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:04:58.954+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:04:58.953+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:04:59.014+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:04:59.001+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:04:59.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:04:59.078+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.152 seconds
[2024-05-18T23:05:29.588+0000] {processor.py:161} INFO - Started process (PID=160) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:05:29.589+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:05:29.592+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:05:29.592+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:05:29.624+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:05:29.618+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:05:29.626+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:05:29.659+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.080 seconds
[2024-05-18T23:06:00.062+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:06:00.065+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:06:00.069+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:06:00.068+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:06:00.107+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:06:00.100+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:06:00.111+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:06:00.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.107 seconds
[2024-05-18T23:06:30.531+0000] {processor.py:161} INFO - Started process (PID=176) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:06:30.533+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:06:30.536+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:06:30.536+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:06:30.577+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:06:30.570+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:06:30.580+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:06:30.609+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.089 seconds
[2024-05-18T23:07:01.001+0000] {processor.py:161} INFO - Started process (PID=184) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:07:01.002+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:07:01.005+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:07:01.005+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:07:01.034+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:07:01.028+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 5, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:07:01.037+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:07:01.066+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.075 seconds
[2024-05-18T23:07:07.200+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:07:07.201+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:07:07.204+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:07:07.203+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:07:09.876+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:07:09.867+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:07:09.880+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:07:09.911+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 2.719 seconds
[2024-05-18T23:07:40.696+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:07:40.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:07:40.700+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:07:40.700+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:07:41.367+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:07:41.358+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:07:41.371+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:07:41.403+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.714 seconds
[2024-05-18T23:08:11.661+0000] {processor.py:161} INFO - Started process (PID=210) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:08:11.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:08:11.667+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:08:11.666+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:08:12.629+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:08:12.619+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:08:12.633+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:08:12.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 1.033 seconds
[2024-05-18T23:08:43.047+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:08:43.049+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:08:43.053+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:08:43.052+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:08:43.962+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:08:43.952+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:08:43.965+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:08:44.001+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.968 seconds
[2024-05-18T23:09:14.549+0000] {processor.py:161} INFO - Started process (PID=228) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:09:14.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:09:14.555+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:09:14.554+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:09:15.306+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:09:15.298+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:09:15.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:09:15.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.797 seconds
[2024-05-18T23:09:45.727+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:09:45.728+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:09:45.731+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:09:45.730+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:09:46.467+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:09:46.459+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:09:46.470+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:09:46.497+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.778 seconds
[2024-05-18T23:10:17.204+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:10:17.206+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:10:17.208+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:10:17.208+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:10:17.802+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:10:17.792+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:10:17.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:10:17.841+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.645 seconds
[2024-05-18T23:10:48.117+0000] {processor.py:161} INFO - Started process (PID=255) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:10:48.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:10:48.120+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:10:48.120+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:10:48.714+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:10:48.707+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:10:48.717+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:10:48.744+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.635 seconds
[2024-05-18T23:11:19.471+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:11:19.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:11:19.476+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:11:19.476+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:11:19.903+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:11:19.895+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:11:19.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:11:19.931+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.467 seconds
[2024-05-18T23:11:50.154+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:11:50.155+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:11:50.157+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:11:50.157+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:11:50.716+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:11:50.708+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:11:50.719+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:11:50.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.596 seconds
[2024-05-18T23:12:21.485+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:12:21.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:12:21.490+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:12:21.489+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:12:22.197+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:12:22.189+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:12:22.200+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:12:22.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.743 seconds
[2024-05-18T23:12:53.083+0000] {processor.py:161} INFO - Started process (PID=291) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:12:53.085+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:12:53.087+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:12:53.086+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:12:53.631+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:12:53.625+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:12:53.634+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:12:53.658+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.583 seconds
[2024-05-18T23:13:24.445+0000] {processor.py:161} INFO - Started process (PID=300) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:13:24.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:13:24.450+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:13:24.449+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:13:25.079+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:13:25.072+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:13:25.082+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:13:25.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.667 seconds
[2024-05-18T23:13:55.187+0000] {processor.py:161} INFO - Started process (PID=309) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:13:55.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:13:55.191+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:13:55.191+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:13:55.950+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:13:55.935+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:13:55.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:13:55.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.804 seconds
[2024-05-18T23:14:26.333+0000] {processor.py:161} INFO - Started process (PID=318) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:14:26.334+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:14:26.337+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:14:26.337+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:14:26.933+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:14:26.927+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:14:26.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:14:26.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.632 seconds
[2024-05-18T23:14:57.263+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:14:57.265+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:14:57.268+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:14:57.267+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:14:57.836+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:14:57.827+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:14:57.839+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:14:57.863+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.605 seconds
[2024-05-18T23:15:28.577+0000] {processor.py:161} INFO - Started process (PID=336) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:15:28.579+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:15:28.581+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:15:28.581+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:15:29.180+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:15:29.172+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:15:29.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:15:29.209+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.639 seconds
[2024-05-18T23:29:25.189+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:29:25.192+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:29:25.204+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:29:25.203+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:29:28.575+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:29:28.567+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:29:28.578+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:29:28.602+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 3.434 seconds
[2024-05-18T23:29:58.728+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:29:58.730+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:29:58.733+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:29:58.732+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:29:59.176+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:29:59.168+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:29:59.180+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:29:59.203+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.483 seconds
[2024-05-18T23:30:29.278+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:30:29.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:30:29.284+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:30:29.283+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:30:29.697+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:30:29.690+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:30:29.700+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:30:29.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.453 seconds
[2024-05-18T23:31:00.062+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:31:00.064+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:31:00.072+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:31:00.071+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:31:00.703+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:31:00.692+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:31:00.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:31:00.740+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.687 seconds
[2024-05-18T23:31:31.124+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:31:31.126+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:31:31.130+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:31:31.130+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:31:31.841+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:31:31.832+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:31:31.844+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:31:31.869+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.752 seconds
[2024-05-18T23:32:02.564+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:32:02.566+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:32:02.569+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:32:02.569+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:32:03.113+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:32:03.106+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:32:03.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:32:03.139+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.581 seconds
[2024-05-18T23:32:33.218+0000] {processor.py:161} INFO - Started process (PID=92) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:32:33.220+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:32:33.222+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:32:33.222+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:32:33.776+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:32:33.769+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:32:33.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:32:33.801+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.589 seconds
[2024-05-18T23:33:04.505+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:33:04.506+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:33:04.510+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:33:04.510+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:33:05.036+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:33:05.023+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:33:05.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:33:05.084+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.587 seconds
[2024-05-18T23:33:35.296+0000] {processor.py:161} INFO - Started process (PID=116) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:33:35.299+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:33:35.304+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:33:35.303+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:33:35.849+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:33:35.839+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:33:35.853+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:33:35.879+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.603 seconds
[2024-05-18T23:34:06.288+0000] {processor.py:161} INFO - Started process (PID=125) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:34:06.290+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:34:06.293+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:34:06.292+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:34:07.074+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:34:07.065+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:34:07.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:34:07.109+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.829 seconds
[2024-05-18T23:34:38.134+0000] {processor.py:161} INFO - Started process (PID=134) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:34:38.136+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:34:38.139+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:34:38.138+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:34:38.762+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:34:38.753+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/premier_league_matches.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/premier_league_matches.py", line 7, in <module>
    from statsbombpy import sb
ModuleNotFoundError: No module named 'statsbombpy'
[2024-05-18T23:34:38.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:34:38.791+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 0.665 seconds
[2024-05-18T23:52:46.933+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:52:46.941+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:52:46.950+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:52:46.949+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:52:57.812+0000] {processor.py:840} INFO - DAG(s) 'last_premier_league_matches' retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:52:58.229+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:52:58.227+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:last_premier_league_matches
[2024-05-18T23:52:58.281+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:52:58.280+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:last_premier_league_matches
[2024-05-18T23:52:58.311+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:52:58.310+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:last_premier_league_matches
[2024-05-18T23:52:58.314+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:52:58.313+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-18T23:52:58.365+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:52:58.359+0000] {dag.py:3118} INFO - Creating ORM DAG for last_premier_league_matches
[2024-05-18T23:52:58.370+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:52:58.369+0000] {dag.py:3954} INFO - Setting next_dagrun for last_premier_league_matches to None, run_after=None
[2024-05-18T23:52:58.470+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 11.612 seconds
[2024-05-18T23:53:28.778+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:53:28.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:53:28.784+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:53:28.783+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:53:31.921+0000] {processor.py:840} INFO - DAG(s) 'last_premier_league_matches' retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:53:32.239+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:53:32.226+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-18T23:53:32.346+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:53:32.345+0000] {dag.py:3954} INFO - Setting next_dagrun for last_premier_league_matches to None, run_after=None
[2024-05-18T23:53:32.574+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 3.819 seconds
[2024-05-18T23:54:03.389+0000] {processor.py:161} INFO - Started process (PID=72) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:54:03.392+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:54:03.412+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:54:03.411+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:54:10.746+0000] {processor.py:840} INFO - DAG(s) 'last_premier_league_matches' retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:54:11.094+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:54:11.092+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-18T23:54:11.251+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:54:11.245+0000] {dag.py:3954} INFO - Setting next_dagrun for last_premier_league_matches to None, run_after=None
[2024-05-18T23:54:11.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 8.097 seconds
[2024-05-18T23:54:43.441+0000] {processor.py:161} INFO - Started process (PID=81) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:54:43.457+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:54:43.468+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:54:43.461+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:54:51.523+0000] {processor.py:840} INFO - DAG(s) 'last_premier_league_matches' retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:54:51.723+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:54:51.722+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-18T23:54:51.826+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:54:51.817+0000] {dag.py:3954} INFO - Setting next_dagrun for last_premier_league_matches to None, run_after=None
[2024-05-18T23:54:51.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 8.629 seconds
[2024-05-18T23:55:23.384+0000] {processor.py:161} INFO - Started process (PID=96) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:55:23.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:55:23.391+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:55:23.391+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:55:28.273+0000] {processor.py:840} INFO - DAG(s) 'last_premier_league_matches' retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:55:28.376+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:55:28.372+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-18T23:55:28.435+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:55:28.435+0000] {dag.py:3954} INFO - Setting next_dagrun for last_premier_league_matches to None, run_after=None
[2024-05-18T23:55:28.563+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 5.201 seconds
[2024-05-18T23:55:59.438+0000] {processor.py:161} INFO - Started process (PID=105) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:55:59.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:55:59.460+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:55:59.459+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:56:06.449+0000] {processor.py:840} INFO - DAG(s) 'last_premier_league_matches' retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:56:06.537+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:56:06.525+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-18T23:56:06.599+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:56:06.599+0000] {dag.py:3954} INFO - Setting next_dagrun for last_premier_league_matches to None, run_after=None
[2024-05-18T23:56:06.711+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 7.297 seconds
[2024-05-18T23:56:29.155+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:56:29.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:56:29.243+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:56:29.242+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:56:38.876+0000] {processor.py:840} INFO - DAG(s) 'last_premier_league_matches' retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:56:39.043+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:56:39.035+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-18T23:56:39.170+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:56:39.170+0000] {dag.py:3954} INFO - Setting next_dagrun for last_premier_league_matches to None, run_after=None
[2024-05-18T23:56:39.440+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 10.334 seconds
[2024-05-18T23:57:11.811+0000] {processor.py:161} INFO - Started process (PID=142) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:57:11.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:57:11.853+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:57:11.852+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:57:22.212+0000] {processor.py:840} INFO - DAG(s) 'last_premier_league_matches' retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:57:22.675+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:57:22.673+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-18T23:57:22.837+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:57:22.836+0000] {dag.py:3954} INFO - Setting next_dagrun for last_premier_league_matches to None, run_after=None
[2024-05-18T23:57:23.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 11.392 seconds
[2024-05-18T23:57:54.384+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:57:54.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:57:54.460+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:57:54.444+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:58:07.795+0000] {processor.py:840} INFO - DAG(s) 'last_premier_league_matches' retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:58:09.499+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:58:09.497+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-18T23:58:09.642+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:58:09.641+0000] {dag.py:3954} INFO - Setting next_dagrun for last_premier_league_matches to None, run_after=None
[2024-05-18T23:58:10.067+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 15.863 seconds
[2024-05-18T23:58:41.247+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:58:41.253+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:58:41.273+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:58:41.261+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:58:48.053+0000] {processor.py:840} INFO - DAG(s) 'last_premier_league_matches' retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:58:48.181+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:58:48.179+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-18T23:58:48.254+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:58:48.254+0000] {dag.py:3954} INFO - Setting next_dagrun for last_premier_league_matches to None, run_after=None
[2024-05-18T23:58:48.564+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 7.359 seconds
[2024-05-18T23:59:20.512+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:59:20.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-18T23:59:20.541+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:59:20.529+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:59:28.137+0000] {processor.py:840} INFO - DAG(s) 'last_premier_league_matches' retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-18T23:59:28.359+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:59:28.346+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-18T23:59:28.481+0000] {logging_mixin.py:188} INFO - [2024-05-18T23:59:28.480+0000] {dag.py:3954} INFO - Setting next_dagrun for last_premier_league_matches to None, run_after=None
[2024-05-18T23:59:28.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 8.465 seconds
[2024-05-19T00:00:00.146+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/premier_league_matches.py
[2024-05-19T00:00:00.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/premier_league_matches.py for tasks to queue
[2024-05-19T00:00:00.450+0000] {logging_mixin.py:188} INFO - [2024-05-19T00:00:00.239+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/premier_league_matches.py
[2024-05-19T00:00:21.745+0000] {processor.py:840} INFO - DAG(s) 'last_premier_league_matches' retrieved from /opt/airflow/dags/premier_league_matches.py
[2024-05-19T00:00:22.305+0000] {logging_mixin.py:188} INFO - [2024-05-19T00:00:22.304+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-19T00:00:22.694+0000] {logging_mixin.py:188} INFO - [2024-05-19T00:00:22.694+0000] {dag.py:3954} INFO - Setting next_dagrun for last_premier_league_matches to None, run_after=None
[2024-05-19T00:00:23.130+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/premier_league_matches.py took 23.087 seconds
