[2024-05-22T22:13:43.415+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T22:13:43.455+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dataset.extraccion manual__2024-05-22T22:09:25.534916+00:00 [queued]>
[2024-05-22T22:13:43.470+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dataset.extraccion manual__2024-05-22T22:09:25.534916+00:00 [queued]>
[2024-05-22T22:13:43.471+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 7
[2024-05-22T22:13:43.495+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extraccion> on 2024-05-22 22:09:25.534916+00:00
[2024-05-22T22:13:43.506+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=458) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-22T22:13:43.508+0000] {standard_task_runner.py:63} INFO - Started process 482 to run task
[2024-05-22T22:13:43.509+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dataset', 'extraccion', 'manual__2024-05-22T22:09:25.534916+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dataset.py', '--cfg-path', '/tmp/tmp7z_rsjvm']
[2024-05-22T22:13:43.512+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask extraccion
[2024-05-22T22:13:43.588+0000] {task_command.py:426} INFO - Running <TaskInstance: kaggle_dataset.extraccion manual__2024-05-22T22:09:25.534916+00:00 [running]> on host 3943db1ddae8
[2024-05-22T22:13:43.743+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dataset' AIRFLOW_CTX_TASK_ID='extraccion' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T22:09:25.534916+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T22:09:25.534916+00:00'
[2024-05-22T22:13:43.745+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T22:13:43.775+0000] {logging_mixin.py:188} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/***/.kaggle/kaggle.json'
[2024-05-22T22:13:47.318+0000] {logging_mixin.py:188} INFO - Global Economy Indicators.csv
[2024-05-22T22:13:47.319+0000] {logging_mixin.py:188} INFO - hecho
[2024-05-22T22:13:47.323+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-22T22:13:47.325+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T22:13:47.340+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=kaggle_dataset, task_id=extraccion, run_id=manual__2024-05-22T22:09:25.534916+00:00, execution_date=20240522T220925, start_date=20240522T221343, end_date=20240522T221347
[2024-05-22T22:13:47.383+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-22T22:13:47.423+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22T22:13:47.426+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
