[2024-05-22T01:16:20.330+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-22T01:16:20.676+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_dataset.extraccion manual__2024-05-22T01:16:10.864259+00:00 [queued]>
[2024-05-22T01:16:20.709+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_dataset.extraccion manual__2024-05-22T01:16:10.864259+00:00 [queued]>
[2024-05-22T01:16:20.715+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 5
[2024-05-22T01:16:20.760+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extraccion> on 2024-05-22 01:16:10.864259+00:00
[2024-05-22T01:16:20.778+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-22T01:16:20.783+0000] {standard_task_runner.py:63} INFO - Started process 93 to run task
[2024-05-22T01:16:20.781+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kaggle_dataset', 'extraccion', 'manual__2024-05-22T01:16:10.864259+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/kaggle_dataset.py', '--cfg-path', '/tmp/tmpjo29h4dq']
[2024-05-22T01:16:20.791+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask extraccion
[2024-05-22T01:16:20.918+0000] {task_command.py:426} INFO - Running <TaskInstance: kaggle_dataset.extraccion manual__2024-05-22T01:16:10.864259+00:00 [running]> on host b17c52120858
[2024-05-22T01:16:21.167+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_dataset' AIRFLOW_CTX_TASK_ID='extraccion' AIRFLOW_CTX_EXECUTION_DATE='2024-05-22T01:16:10.864259+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-22T01:16:10.864259+00:00'
[2024-05-22T01:16:21.170+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-22T01:16:21.264+0000] {logging_mixin.py:188} INFO - Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /home/***/.kaggle/kaggle.json'
[2024-05-22T01:16:25.856+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-22T01:16:25.859+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-22T01:16:25.891+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=kaggle_dataset, task_id=extraccion, run_id=manual__2024-05-22T01:16:10.864259+00:00, execution_date=20240522T011610, start_date=20240522T011620, end_date=20240522T011625
[2024-05-22T01:16:25.961+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-22T01:16:26.053+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-22T01:16:26.058+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
